### ISSUE TITLE
Feature: `dynamic.resolutionsInclude` or something

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/trace-pkg#28]
Our current `dynamic.resolutions` configuration allows for specifying new _JS imports_ to match dynamic import misses. A slightly different problem is when a library does something like `const style = fs.readFileSync("./a-style.css")` or something. We won't get dynamic import miss, and we can fix the situation with a normal non-parsed `include` but that needs the relative to CWD path to the file...

Instead, it would be great to have a more portable option that was relative to a file to include something that isn't parsed. Could look something like:

```yml
dynamic:
  resolutions:
    "a-pkg": ["./real-js.js"] # This file _is_ parsed
  resolutionsInclude:
    "a-pkg": ["./a-style.css"] # This file is _not_ parsed
```

Such a feature doesn't have to be part of `dynamic.*` at all because it's not part of the dynamic import misses. So maybe a top-level field or something instead?
